# Generated by Django 4.1.1 on 2022-11-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time2', models.CharField(max_length=10, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
                'db_table': 'schedule',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Pets',
        ),
        migrations.AlterModelOptions(
            name='sign_up',
            options={'managed': False, 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterModelTable(
            name='sign_up',
            table='sign_up',
        ),
    ]
