# Generated by Django 4.0 on 2022-11-28 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_schedule_delete_pets_alter_sign_up_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
